# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bearer < Formula
  desc "A data-first security scanner that finds risks and vulnerabilities in your code so you can protect sensitive data (PHI, PD, PII)."
  homepage "https://bearer.com"
  version "1.51.1"
  license "Elastic License 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bearer/bearer/releases/download/v1.51.1/bearer_1.51.1_darwin_amd64.tar.gz"
      sha256 "f1fabc739367b4ef60433e7cbd416398cbaa5f0fdb14a551386d747e849f8c1b"

      def install
        bin.install "bearer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bearer/bearer/releases/download/v1.51.1/bearer_1.51.1_darwin_arm64.tar.gz"
      sha256 "96ce811d6e706664eae84bb4f04228ec67638bdc17b696fa8447a4a3b0615162"

      def install
        bin.install "bearer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Bearer/bearer/releases/download/v1.51.1/bearer_1.51.1_linux_amd64.tar.gz"
      sha256 "f61a4903db2f9f0842e630013a2bb0c7fa8bd924639e55f991b865d34de4d786"

      def install
        bin.install "bearer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bearer/bearer/releases/download/v1.51.1/bearer_1.51.1_linux_arm64.tar.gz"
      sha256 "ef3759a63eb621ea203bc5a938fcea192557b4d72a3e23e1238e7167b0afd330"

      def install
        bin.install "bearer"
      end
    end
  end
end
